### ISSUE TITLE
Missing "category" column in dataframe

### ISSUE THREAD

**Issue by dalphajw** [glami/glami-1m#2]
First of all, thank you for open-sourcing this repository. I have just one question.
I recently downloaded the dataset and tried to run the eval_embracenet.py example.
However, I ran into a problem where the dataset raised an error while loading due to COL_NAME_CATEGORY ("category") not existing.

['item_id', 'image_id', 'name', 'description', 'geo', 'category_name', 'label_source', 'image_file'] seems to be what I get when I run df.keys() after line 19 in eval_embracenet.py.

Thank you in advance. I look forward to hearing from you soon.

**Comment by vackosar** [comment]
Hello, thank you for your report. I added the column to the list.

This column is not that helpful, because it is not a true integer index and as can be seen in the code the EmbraceNet converts the column of number to another set of numbers for indexing (`label_binarizer`). For other use-cases, I recommend using `category_name` column (`COL_NAME_CAT_NAME`) and create your own indexing from that.

Please let me know if you have any more issues.

**Comment by dalphajw** [comment]
Thank you so much for the prompt response. I did realize (albeit a bit late) that the column wasn't actually not a major factor 😅
Anyhow, I do not have any other issues atm and I think I can close this issue as it has been solved.
Thank you again for your work on GLAMI-1M.

**Comment by vackosar** [comment]
My pleasure! I am very happy that people are finding the dataset useful contribution.
